name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'setup buildx'
        uses: docker/setup-buildx-action@v1

      - name: 'build'
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
