name: 'build'

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 'release'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'build'
        uses: docker/build-push-action@v2
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: $GITHUB_REPOSITORY
          platforms: linux/amd64,linux/arm64
          tags: latest
